### ISSUE TITLE
Callback revived on incorrect window

### ISSUE THREAD

**Issue by henninglive** [verto-health/ngx-turnstile#38]
Rapidly creating NgxTurnstileComponents may cause the window callback to be received on another window. The turnstile script may not be loaded on the new window.

Example:

```typescript

export class NgxTurnstileComponent implements AfterViewInit, OnDestroy {

  public ngAfterViewInit(): void {
    console.log('ngAfterViewInit', self.window.name);
    
    let turnstileOptions: TurnstileOptions = ...

    window[CALLBACK_NAME] = () => {
      if (!this.elementRef?.nativeElement) {
        return;
      }

      console.log('callback', self.window.name)
      
      this.widgetId = window.turnstile.render(
        this.elementRef.nativeElement,
        turnstileOptions,
      );
    };

    if (this.scriptLoaded()) {
      window[CALLBACK_NAME]();
      return;
    }

    ...
  }
}

```

```typescript
import { ComponentFixture, TestBed } from '@angular/core/testing';
import { NgxTurnstileComponent } from './ngx-turnstile.component';

describe('NgxTurnstileComponent', () => {
  let component: NgxTurnstileComponent;
  let fixture: ComponentFixture<NgxTurnstileComponent>;

  let run = 1;
  beforeEach(async () => {
    window.name = 'test-' + run++;
    await TestBed.configureTestingModule({
      imports: [NgxTurnstileComponent],
    }).compileComponents();

    fixture = TestBed.createComponent(NgxTurnstileComponent);
    component = fixture.componentInstance;
    component.siteKey = '1x00000000000000000000AA'
    fixture.detectChanges();
  });

  it(`should create 1`, () => {
    expect(component).toBeTruthy();
  });

  it(`should create 2`, () => {
    expect(component).toBeTruthy();
  });

});
```

```
NgxTurnstileComponent
✅should create 1
❌should create 2

LOG: ngAfterViewInit test-1
LOG: ngAfterViewInit test-2
LOG: callback test-2
LOG: callback test-2

TypeError: Cannot read properties of undefined (reading 'render')
    at window.<computed> (http://localhost:9876/_karma_webpack_/webpack:/src/app/ngx-turnstile/ngx-turnstile.component.ts:110:40)
    at NgxTurnstileComponent.call [as ngAfterViewInit] (http://localhost:9876/_karma_webpack_/webpack:/src/app/ngx-turnstile/ngx-turnstile.component.ts:117:28)
    at callHookInternal (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2022/core.mjs:5153:14)
    at callHook (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2022/core.mjs:5180:13)
    at callHooks (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2022/core.mjs:5134:17)
    at executeInitAndCheckHooks (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2022/core.mjs:5084:9)
    at refreshView (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2022/core.mjs:13858:21)
    at detectChangesInView (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2022/core.mjs:13999:9)
    at detectChangesInViewWhileDirty (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2022/core.mjs:13694:9)
    at detectChangesInternal (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm2022/core.mjs:13673:9)
```

**Comment by choyiny** [comment]
@henninglive what is the use case of rapidly creating many turnstile widgets at once? Do you have a production use-case where this is important?

**Comment by henninglive** [comment]
@choyiny it's mainly an issue in test code.

We encountered the problem when writing unit tests for Angular components containing a NgxTurnstileComponent. Since jasmine unit tests typical recreate the component between each test case, we would consistently receive callbacks after the NgxTurnstileComponent had been destroyed or on a different NgxTurnstileComponent.

**Comment by sut123** [comment]
This could likely be resolved using something to track whether the component is still active. Angular just recently added that takeUntilDestroyed() feature, something like that could work.
Note: I haven't tested this at all, but it sounds plausible;
